name: Java CI with Maven

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '20'

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run tests
      run: mvn -B test
